### ISSUE TITLE
Traps may crush monster data

### ISSUE THREAD

**Issue by ssakusha** [SLASHEM-Extended/SLASHEM-Extended#11]
Hello.
I discover serious concern at source codes.

Monsters knows trap with data area "mon->mtrapseen".
If monster trapped, the monster knows its trap type. See trap.c:

>            mtmp->mtrapseen |= (1 << (tt - 1));

But, see monst.h:

>    long mtrapseen; /* bitmap of traps we've been trapped in */

I fear that other data may break with it, if trap numbers over "sizeof(long)".
Please check it.

  #Note: FHS patch handles it temporaly.(see #ifdef HONEY_OVERFLOWED_TRAP)
  #But it has only under 64 traps.
  #And Slash'EM Extended has over 200 traps...

**Comment by moon-chilled** [comment]
Thanks for the report.  I'm pretty sure the best way to handle this is to make multiple bitmaps for that (mtrapseen1, mtrapseen2, mtrapseen3, mtrapseen4) and then a couple of macros: settrapseen and istrapseen that automatically choose the right one.

**Comment by AmyBSOD** [comment]
Oh! This may be the source of savegame errors and the like! Great find, I'll need to look into it and see how to best fix it! Also, it's nice to actually meet the FHS developer, I've "stolen" many features from your variant. :-) Are you still actively developing it?

**Comment by AmyBSOD** [comment]
Fixed by commit 20cbbf3.
