### ISSUE TITLE
date.h not found in cmd.c

### ISSUE THREAD

**Issue by MichaelMacha** [SLASHEM-Extended/SLASHEM-Extended#12]
In cmd.c, there is an include listed for "date.h"; no such file is present in that directory. This makes make, let alone compilation, impossible.

Current system is Linux Mint 18.1.

I am currently searching for a workaround.

**Comment by AmyBSOD** [comment]
What? It works for me... date.h is generated during compilation, by "makedefs" to be specific, what operating system are you trying to compile it on?

**Comment by MichaelMacha** [comment]
As I said, Linux Mint 18.1. I might be compiling it wrong; but I have followed the instructions on nethackwiki for Debian/Ubuntu. 

Instead of a package, I consistently get this:

========================= Installation results ===========================
( cd src ; make )
make[1]: Entering directory '/home/michael/src/SLASHEM-Extended/src'
cc -g -O2 -I../include   -c -o cmd.o cmd.c
cmd.c:8:18: fatal error: date.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'cmd.o' failed
make[1]: *** [cmd.o] Error 1
make[1]: Leaving directory '/home/michael/src/SLASHEM-Extended/src'
Makefile:168: recipe for target 'slex' failed
make: *** [slex] Error 2

****  Installation failed. Aborting package creation.

**Comment by moon-chilled** [comment]
Do dis:

    $ cd ~/src
    $ rm -rf SLASHEM-Extended
    $ git clone https://github.com/SLASHEM-Extended/SLASHEM-Extended
    $ cd SLASHEM-Extended
    $ sh sys/unix/setup.sh
    $ make all

If that doesn't work then repeat everything up to (not including) `sh sys/unix/setup.sh`.  Then do `make -f sys/unix/GNUmakefile`.

**Comment by MichaelMacha** [comment]
That did it. My specific command sequence (along with a few cups of coffee) was:

$ cd ~/src
$ rm -rf SLASHEM-Extended
$ git clone https://github.com/SLASHEM-Extended/SLASHEM-Extended
$ cd SLASHEM-Extended
$ make -f sys/unix/GNUmakefile
$ sh sys/unix/setup.sh
$ make all
$ make install

And now slex is running smoothly.
