### ISSUE TITLE
Player and monster characters sometimes leave behind persistent trails

### ISSUE THREAD

**Issue by oddhack** [SLASHEM-Extended/SLASHEM-Extended#21]
Unix SlashEMExtended Version 2.1.1 (1e52c62b) - last build Thu Nov 16 18:46:30
2017

I recently restarted a saved game and started seeing behavior where both the player, and monsters would leave behind persistent instances of their character on the tty, as in the following example:

```
Do you really want to step into that arrow trap? [yn] (n) n



            #######################################┌─────────────┐
           ##,,,,,,,,,,,@@,,,,,,,,,,,,,,,,,,,,,,,@ f·············│
     ┌─────┐,,#┌─ff──────────┐#####################│········ ····│
     │·····q,#┌┘·············└┐##    ┌───┐     ###, ·············│
     │·qY··│##│······┌─┐······ ,#┌ ──┘···└── ┐ #,,,└ ────────────┘
     │·····│#, ······│ │······│,#│····· ·····│##,###,#
     └──@──┘, │······└─┘······│,,│···┌ ──┐···│,,,# #,###
       #,,,#, └┐··· ·········┌┘#,│···│·  │···│,### #,,,#
      ┌─── ┐,,#└─────────────┘ #,│·· │ · │ ··│,#   ###,#
      │···· ,,,,               #,│···│· ·│··· ,#     #,#
      │····│, #                #,│···└───┘···│##     #,##
      │···· ,#                 #, %···· ·····│       #,,#
      │····│##                 ##└ ──┐···┌── ┘      ┌── ───┐
      │··· │                         └───┘          │      │
      └────┘                                        │      │
                                                    │      │
                                                    └──────┘

[Jon the Cop Chief]  St18/06 Dx17 Co15 In15 Wi10 Ch8 OffAsgFemNeu
Dlvl:9 $2 HP416(416) Pw256(256) AC-19 Exp30 T36456 Sat
```

Here, the Upper-rightmost '@' is the actual player, while the other 3 @ are places I had moved from, and encountered something. Similarly, the two 'f', two 'q', and one 'Y' are all monsters leaving behind a trail. I've tried resetting the xterm, opening a new xterm, saving and restarting the game, but the problem keeps showing up.

If I go back up a level and then down, or refresh (^R), the dungeon is painted with blank spaces in the places where monsters, traps, staircases, etc. ought to be rendered (for example, there's a trap in the lower-right corner of the lower-left room, but rendered as a blank space, as can be seen above).

This is really weird behaviour. Any idea what's up?

**Comment by oddhack** [comment]
N.b. I believe this started when I emerged from the Sokoban levels, which can be reached from level 9 which the screencap above is on. But the behavior happens on other levels as well.

**Comment by AmyBSOD** [comment]
You triggered a RMB loss trap. Works as intended. It will time out after a random amount of turns.
