### ISSUE TITLE
evilvariant crash

### ISSUE THREAD

**Issue by Ozma777** [SLASHEM-Extended/SLASHEM-Extended#23]
crash in the first room fighting a ghost.
I originally recovered it and then savescummed to see if it kept happening (it did).
(not sure if the attachment worked)
https://www.sendspace.com/file/3l24g1

Nice job on the poisoned well, I was thinking of that after seeing the comments on the DES file for the orc overridden Frontier Town.

Also I can't seem to send you private messages anymore, did rpgnet change stuff?

**Comment by AmyBSOD** [comment]
Sorry about that crash, it's been fixed in development already and I will push the fix on Monday. I have no need for the savegame file though; please only upload savegame files if I specifically request them.

Weird, I'm not aware of any change to the private messaging function, and my inbox isn't full either...

**Comment by AmyBSOD** [comment]
The reason is that if the player is fighting bare-handed, a faulty check simply assumes the player has a weapon, causing a segfault due to an uninitialized pointer.

**Comment by AmyBSOD** [comment]
Fixed by commit a66c899. Sorry for inserting such a stupid bug and being too slow with fixing it (when I realized that the crash was there, I hoped to get the fix out before anyone would notice :D).

**Comment by Ozma777** [comment]
ah so I should (until I download the new version) just equip a weapon and/or kick things to death to not have it crash?

also forum.rpg.net JUST disabled PMs for people who do not have 10 posts.

I have nothing to post yet, so I have to come up with 8 more nonspam/noncrap posts in order to be able to PM again.

Do you know if Elrond has taken a look at the code (folder I sent him named Slashem3-10152017) to see if he can help fix my broken code?
Next up I'd like to add non-square rooms and SlashTHEM random room colors (solid colors) as well as grunthack's terrain in mine's levels.
--------------------------------------------
On Sat, 2/10/18, AmyBSOD <notifications@github.com> wrote:

 Subject: Re: [SLASHEM-Extended/SLASHEM-Extended] evilvariant crash (#23)
 To: "SLASHEM-Extended/SLASHEM-Extended" <SLASHEM-Extended@noreply.github.com>
 Cc: "Ozma777" <spam12828v28v@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Saturday, February 10, 2018, 6:25 PM
 
 The reason is that if the player
 is fighting bare-handed, a faulty check simply assumes the
 player has a weapon, causing a segfault due to an
 uninitialized pointer.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by AmyBSOD** [comment]
You should upgrade to the newest version ASAP, although if there was a savebreak in between, you won't be able to load that old save. Apart from that, yeah, unfortunately the bugged version will always crash if you don't have anything in the weapon slot and try to melee something. Sorry about the bug!
