### ISSUE TITLE
Farlook (pressing ;) prompts --more-- in windowtype curses

### ISSUE THREAD

**Issue by kenakofer** [SLASHEM-Extended/SLASHEM-Extended#26]
When I press the semicolon to farlook in the curses windowtype, --more-- shows in the pager and I have to press another key before moving the cursor. When the pager is full, the --more-- seems to only have its first "-" visible on the right edge of the pager.

**Comment by AmyBSOD** [comment]
The current version should allow you to disable the "moreforced" option (it defaults to on) which disables all those forced --More-- prompts.
