### ISSUE TITLE
Can't Save

### ISSUE THREAD

**Issue by MetaNite64** [SLASHEM-Extended/SLASHEM-Extended#29]
I started a game normally, and I needed to leave. I pressed S, and it prompted me "Do you really want to save? [y/n]" like normal. I pressed y, and it said "Saving... Cannot open save file." Please help!

**Comment by AmyBSOD** [comment]
Context? It would help if I knew whether you're playing offline or on a server, and if the former, whether it's Windows, Unix or something else... from the report you've given, I can only guess :( But my guess would be that you're playing offline on Unix, and the message means it's either not installed correctly or you don't have permissions to save into the folder you installed it to, in which case you need to use the "chown" command on the folder.

**Comment by MetaNite64** [comment]
Oh, sorry. I'm playing offline, on a Debian-based system (most likely just Debian). I installed the Debian package instead of cloning the files through git. Should I try that instead?

**Comment by AmyBSOD** [comment]
Uhh. Beats me. I'm not familiar with Debian systems myself. Your best bet would be to join us on Freenode IRC, we hang around in the #em.slashem.me channel. Elronnd and possibly others will probably be able to troubleshoot this much better than I ever could. Thanks for your interest in the game, and hopefully we can help you get it to run! :)

**Comment by MetaNite64** [comment]
Thanks!

**Comment by moon-chilled** [comment]
Hi, did you get your debian package from the page linked [here](https://nethackwiki.com/wiki/Slash'EM_Extended#Obtaining)?  Because if so, that's years out of date, so you wouldn't want to play on it anyway.  I would try downloading the source via github and compiling it yourself (run `make -f sys/unix/GNUmakefile install`) and see if that works.
