### ISSUE TITLE
Entering New Sokoban Level Cloned My Party?

### ISSUE THREAD

**Issue by Litostorg** [SLASHEM-Extended/SLASHEM-Extended#3]
No idea if this is a bug or just an entertaining feature (can't find it documented), but went up a dungeon level in sokoban and my character and all 5 of my pets got created as additional hostile monsters. Certain equipped and some top level inventory items seem to have been copied across but no non-empty containers (fine), which obviously leads me to belief it's intentional. Unfortunately of the two weapons i had in the top level inventory +0 crysknife and +1 elven bow only the +1 elven bow got copied across (cursed) so also given i was polymorphed into a chasme, i had no problem dispatching my (non-polymorphed) clone and for some reason my 4 chasmes dispatched the 4 copied chasmes very easily as well as a couple of other monsters that were generated. Can't help feeling this  encounter should have been more difficult but given all my sleep attacks [can't remember how many procced] maybe i was just lucky??

**Comment by AmyBSOD** [comment]
huh. That's very weird and actually not intentional, but I think I know what's causing this... apparently the pets are re-created on changing dungeon levels?! Will definitely look into this, and probably fix it in the next release. Thanks for discovering this! :)

**Comment by AmyBSOD** [comment]
Cannot replicate this, but for the time being I'll leave it open. If it happens again I'll have to look into what exactly is happening code-wise when pets change levels...

**Comment by AmyBSOD** [comment]
Maybe it was a bones level from a previous attempt with the same character? In slex, bones levels are possible in Sokoban.

**Comment by Litostorg** [comment]
Thanks for looking into it, yes this might well be down to me save scumming, so feel free to close and i'll reopen if it happens again (i'll be more careful with bones files in future).

**Comment by AmyBSOD** [comment]
This certainly looks like a side effect of save scumming. It has never appeared anywhere else, so I'm closing it for now.
