### ISSUE TITLE
Occasional segmentation fault in character generation in Linux

### ISSUE THREAD

**Issue by BarclayII** [SLASHEM-Extended/SLASHEM-Extended#4]
GDB gives the following output:
0x0000000000717a60 in u_init () at u_init.c:15445
15445       starlitu->mmove = mons[starlitmonster].mmove;

**Comment by BarclayII** [comment]
Apparently the `starlitu` variable is pointing to `PM_TRUE_MISSINGNO` monster, whose attributes are obtained _beyond_ `mons[]` array.  I think this is a quite dangerous, if intended, design, and needs some control, since the name of monster could be a NULL pointer, or the `mlet` could be a NULL character, etc.

**Comment by AmyBSOD** [comment]
Whoa! That's very helpful, I was wondering why this was happening and now I might be able to figure it out so I can squash the bug! Thanks a lot!

**Comment by AmyBSOD** [comment]
It probably depends on the size of the executable file that holds the monster records, and how far the data extends beyond the monsters array. Using a safety mechanism that makes sure it never goes more than 10000 entries beyond the array seems to prevent the crash from happening; during my test run it started to become very crashy at about 33000 beyond, but it might depend on the platform used so I'll use a lower limit just to make sure. By extension, this means that the missingno race can probably crash too if they try to poly into something far beyond the mons[] array, this will be fixed as well.

**Comment by BarclayII** [comment]
Or we can probably just generate the `TRUE_MISSINGNO` race with pure random content to approximate the intended behavior, as loading the attributes with deliberate glitch seems too dangerous:

``` C
for (unsigned char *byte = (unsigned char *)starlitu; byte < starlitu + 1; ++byte) {
    *byte = rn2(256);
}
/* Or replace the mname field with other valid contents */
starlitu->mname = "True Missingno.";
/* Avoid '\r', '\n' etc. which may break screen drawing */
starlitu->mlet = (char)(rn2(256 - (int)' ') + (int)(' '));
/* ... */
```

**Comment by AmyBSOD** [comment]
Hey, that's a nice idea too! I'll probably try to implement that. Thanks! :)

**Comment by AmyBSOD** [comment]
I actually did both: now the "true missingno" still uses the old method of accessing memory past the mons[] array but limited to 10000 entries past, which seemed to be safe during my tests. And there's a new "ethereal missingno" which uses the method of rolling arbitrary values for most of its data. :)

Tentatively setting to fixed in development version; zip archives updated (savebreak), commits will be pushed later (another savebreak due to new content being added over the weekend).

**Comment by AmyBSOD** [comment]
Fixed in v152/153.
