### ISSUE TITLE
Wrong Degradation Message?

### ISSUE THREAD

**Issue by MetaNite64** [SLASHEM-Extended/SLASHEM-Extended#40]
I was fighting an unbearable golem when it gave this strange message: `Your fragrant olive potion rusts!` Obviously, potions cannot rust, so I don't know what is happening here. In my inventory, it is not rusted, but burnt and diluted, so the message but not the action is off here.

**Comment by AmyBSOD** [comment]
Works as intended. You got hit by an antimatter damage effect, which can also damage items that normally can't be damaged. Potions can normally neither rust nor burn (being made of glass; fire damage can boil them directly, but that's different), however those two types of erosion are using the same internal flag, and if the item can't be normally damaged by either, the description just defaults to saying "burnt".

**Comment by AmyBSOD** [comment]
Also I should add that you're playing slex; saying "obviously potions cannot rust" isn't always true. You can get a potion that is made of iron, and then it can rust.
