### ISSUE TITLE
rnd(0) error after panda attack

### ISSUE THREAD

**Issue by KongMD-Steam** [SLASHEM-Extended/SLASHEM-Extended#43]
I'm playing SLEX 2.66 on hardfought. After I summoned these pandas via a cursed scroll of mass murder, I equipped my fly swatter. The panda hit me after that and I got this error message:

![rnd0 Pandas+1](https://user-images.githubusercontent.com/36478131/80762492-2e4f6b00-8b2c-11ea-96da-5c38221581b9.png)

**Comment by AmyBSOD** [comment]
Fixed in https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/e6fb20bdc. Thanks :)
