### ISSUE TITLE
Off-by-one in timebasedlowerchance()

### ISSUE THREAD

**Issue by grantlison** [SLASHEM-Extended/SLASHEM-Extended#45]
[Line 14914 of allmain.c](https://github.com/SLASHEM-Extended/SLASHEM-Extended/blob/master/src/allmain.c#L14914) should use either `rn2` instead of `rnd` or `>=` instead of `>`. As it is all chances are reduced by 1%, with the base success chance reduced from 10 to 9%.

**Comment by AmyBSOD** [comment]
Well, I decided that I like the current values and don't feel like changing them ;) So I clarified the code in https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/da02e12f and if I ever feel the need to adjust the numbers, I can still do so.
