### ISSUE TITLE
Hiding under nothing

### ISSUE THREAD

**Issue by MetaNite64** [SLASHEM-Extended/SLASHEM-Extended#49]
It's pretty easy to end up hiding under nothing. Wear a secret helmet (it's a randomized helmet appearance, not a specific helmet type), which lets you hide under things, and then while you're riding a steed, walk over a corpse. If your steed eats the corpse the same turn that you step onto it, the corpse will disappear, but you will remain hidden. This can also happen if you start eating a corpse but are interrupted by the monster reviving itself.

**Comment by AmyBSOD** [comment]
Yes, this is known, but I decided it's hilarious enough to declare it a feature ;)

**Comment by MetaNite64** [comment]
Ah, gotcha lol
In that case, the issue pivots to just a "Program in disorder" error whenever an enemy tries to move onto your square while you're hiding in nothing.

**Comment by AmyBSOD** [comment]
Fixed by https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/ee17bf7a - now the impossible message should no longer occur :)
