### ISSUE TITLE
Selecting "y" at the "Shall I pick a character's race, role, gender and alignment for you?" prompt crashes the game (bsd)

### ISSUE THREAD

**Issue by moon-chilled** [SLASHEM-Extended/SLASHEM-Extended#7]
This is a strange bug.  On FreeBSD at least, if you select "y" at the prompt that asks you "Shall I pick a character's race, role, gender and alignment for you?", the game seg-faults and gives and exit value of 139.

**Comment by AmyBSOD** [comment]
Missingno initialization bug (again)... probably need to put defines for the missingno range. That way, if there are crashes occurring, the range can be reduced via compilation options. It obviously means less randomization but that's still a heck of a lot better than segfaulting, cause segfaults are no fun at all.

**Comment by AmyBSOD** [comment]
Commit 80a3151 makes the initialization range configurable; it used to always be 10000 but can be changed in config.h now. Try it with 2000 and see if it still crashes, it shouldn't but if it does then decrease it even more.

**Comment by moon-chilled** [comment]
Said commit 80a3151 seems to have fixed the problem
