### ISSUE TITLE
Full-blown crash bug (formerly Phantom crash bug)

### ISSUE THREAD

**Issue by AmyBSOD** [SLASHEM-Extended/SLASHEM-Extended#8]
The worst thing in existence is back; apparently on the new server we're only suffering from a mild form of it, but it's there. What it does is it randomly crashes the game with segfaults, e.g. on changing levels but also when random things happen, I got a crash upon killing a unique & summoned by Moloch. Back in the days this bug also used to rewrite the monster and object arrays, leading to crashes upon wishing, genociding or doing other things that prompt for an item or monster name, but I couldn't reproduce that yet.

This bug does not appear on any of my local Windows or Unix installs, nor does it appear on sade. In fact, it seems to be specific to a certain server architecture or something. There's probably some function that causes it; we were suspecting the pokedex once, and disabled that for public servers, but apparently it didn't completely solve the problem. There may even be several unrelated phantom crash bugs in fact. Anyway, the timed autosave function was added to fight the symptoms of this problem since I can't get to the root of it; let's hope we can eventually find out what's really going on there...

**Comment by moon-chilled** [comment]
It's possible that in this case clang is the problem; on most "local linux installs," gcc would be installed by default and there would be no reason to install clang.  On sade, gcc not clang was used.  The two servers where the phantom crash bug occurred both ran FreeBSD, and thus slex was probably compiled with clang.

**Comment by moon-chilled** [comment]
Marking as sev3 for now (smaller numbers mean worse problems).  Yes, it can ruin a game, but it happens pretty rarely.  And it can be mitigated by enabling PHANTOM_CRASH_BUG in config.h.  And sometimes it only causes small problems.

**Comment by AmyBSOD** [comment]
Happened on Windows now, twice. Changing levels, bam, segfault. And the bug must be happening in a tiny window: come down to (already explored) Mall level, take two steps to the next downstair, try to use it, crash. The other one was when going up the mines and trying to take the stair to the main dungeon. Also, other people's games are crashing. One got a segfault on quaffing from a Minetown fountain and then a "checkpoint data incompletely written" game-ender bug upon trying to recover. What the heck is going on???

**Comment by AmyBSOD** [comment]
Another fountain-quaffing segfault on the server. The player was still on dlvl1, and the ttyrec shows that "Water gushes forth from the overflowing fountain! Everella drowns.End of recording." So it seems quaffing from fountains definitely causes segfaults. Yes, I want fountain-quaffing to be dangerous, since it's something you're simply not supposed to do, but segfaults aren't an appropriate punishment. And my games crashed even though I'm not quaffing from fountains at all so there's something else going wrong, too.

**Comment by AmyBSOD** [comment]
Fountain quaffing bugs resolved. Segfaults on changing levels still remain.

**Comment by AmyBSOD** [comment]
This still exists; random crashes are rare, but unfortunately not gone. After a long crash-free period, a player on the server got a segfault panic while the game tried to autosave on Mines End (the variant with lots of rocks and loadstones). We had to restore from a backup. And it seems that this player got several crashes in Sokoban later on, including one that happened two turns after coming back to the game; the only thing he had done was throwing a ruby to a crossaligned unicorn. A "cannot open <playername>.1 save file" error was also observed when he tried to save. Unfortunately, the cause for these crashes is still unknown.

**Comment by AmyBSOD** [comment]
Possibly happens because the game is making an item via one of the mkobj functions and then simply assumes the item exists, proceeding to perform operations on it. Incidentally this is also how the segfault panic caused by the segfaulter race triggers, except that one's done on purpose. 6332cd4 tries to alleviate the problem but it still happens fairly often if you play the minimalist race...

**Comment by AmyBSOD** [comment]
The random crashes have gone down in frequency, but are not completely eliminated. Very sporadically, it crashes either upon saving (making restoration difficult, argh!), upon entering a new dungeon level (it does not seem to matter whether you enter a previously visited one or a new one) or upon walking around on an existing one. Still suspecting some monster/object/trap generation code not checking whether the entity they create really exists, and then performing operations on it; yet, I have no clue where in the code it happens...

**Comment by AmyBSOD** [comment]
The savegame error may have been fixed by f8885f1 and that may also have been the cause for Paliculo's savegame error in SLASH'EM 0.08. Not really sure if it's the herb growth function that was causing it, or my own dungeon regrowth functions, because gdb was also complaining about the newsym() call.

**Comment by AmyBSOD** [comment]
ac9f3d4 should really fix it. Tentatively closing it for now and REALLY hoping it won't reappear.
